microsoft/maker.js

index.js
src/core/intersect.ts
src/core/maker.ts
src/core/path.ts
src/core/svg.ts
target/js/browser.maker.js
target/js/node.maker.js
target/ts/makerjs.d.ts

this is much easier done with CSS directly, we don't need this construct. Now that id's are on <g> tags.

removed css style property

---

playground/embed.html

try/ catch around parent access.
removed extra buttons.
default to not show origin.

fixes to embedded playground

---

package.json
src/core/maker.ts
target/mk-typings-dir.js
target/version-inside.js

Added version number to executable, add licensify to browser build

version 0.9.9

---

.npmignore
index.d.ts
index.js
package.json
playground/index.html
src/core/layout.ts
src/core/maker.ts
src/core/measure.ts
src/core/solvers.ts
target/js/browser.maker.js
target/tsconfig.json
tsconfig.json

This includes the new layouts feature.

new build 0.9.43

---

index.d.ts
index.js
package.json
src/core/maker.ts
target/js/browser.maker.js
tests/env_browser.htm
tests/env_node.js
tests/env_worker.js

new build 0.9.47

---

index.d.ts
index.js
package.json
src/core/maker.ts
src/core/schema.ts
target/js/browser.maker.js
target/tsconfig.json
tsconfig.json

new build 0.9.49

---

demos/js/pixel-heart.js

Just contributing something fun!

Add model of Pixel Heart 💜 to demos

---

index.d.ts
index.js
package.json
src/core/exporter.ts
src/core/maker.ts
src/core/svg.ts
target/js/browser.maker.js

Added support for layer options in SVG export.
Fixes #248

new build 0.9.51

---

index.d.ts
index.js
package.json
src/core/fillet.ts
src/models/Ring.ts
target/js/browser.maker.js

new build 0.9.54

---

src/core/chain.ts

passing an object implementing IContainChainsOptions instead of a boolean seems to solve a small type error

issue 271 true | IContainChainsOptions 

---

package.json
src/core/openjscad.ts

remove dependency on @types/openjscad

---

_snippets/getting-started-browser.html

Add CDN links

---

index.d.ts
index.js
package-lock.json
package.json
src/core/exporter.ts
target/js/browser.maker.js

 new build 0.9.79

---

index.d.ts
index.js
package-lock.json
package.json
src/core/cascades.ts
src/core/combine.ts
src/core/path.ts
target/js/browser.maker.js

new build 0.9.91

---

index.d.ts
index.js
package-lock.json
package.json
src/models/Text.ts
target/js/browser.maker.js

added makerjs.models.Text.glyphToModel to support #349

new build 0.10.3

---

README.md
docs/_layouts/snippetlist.html
docs/_snippets/distorting.html
docs/docs/intermediate-drawing/index.html
docs/index.html
docs/playground/embed.html
docs/target/js/browser.maker.js
package.json
packages/maker.js/package-lock.json
packages/maker.js/package.json
packages/maker.js/src/core/cascades.ts
packages/maker.js/src/core/chain.ts
packages/maker.js/src/core/model.ts
packages/maker.js/src/core/path.ts
packages/maker.js/src/models/BezierCurve.ts

model.distort

---

packages/docs/package.json
packages/docs/tsconfig.json
packages/maker.js/package.json
packages/maker.js/src/core/dxf.ts
packages/maker.js/target/tsconfig.json
packages/maker.js/tsconfig.json

Separate the actual output of dxf from the parsing structure

Use dxf-parser-typings

---

docs/target/js/browser.maker.js
packages/maker.js/src/core/importer.ts
packages/maker.js/src/core/svg.ts
packages/maker.js/test/importer.js

SVG import #341 
* imports paths with additional coordinates after M (move-to) command
* also imports paths with additional coordinates after L, A, C, S, Q and T commands
* fixed a bug where coordinates with no leading 0 and no space between them were not being read correctly

Svg import (#341)

---

docs/demos/demoify.js
docs/docs/api/interfaces/makerjs.exporter.iflowannotation.html
docs/docs/api/interfaces/makerjs.exporter.isvgelementrenderoptions.html
docs/docs/api/interfaces/makerjs.exporter.isvgpathdatarenderoptions.html
docs/docs/api/interfaces/makerjs.exporter.isvgrenderoptions.html
docs/docs/api/interfaces/makerjs.importer.isvgimportoptions.html
docs/docs/api/modules/makerjs.exporter.html
docs/docs/api/modules/makerjs.importer.html
docs/target/js/browser.maker.js
packages/maker.js/package-lock.json
packages/maker.js/package.json
packages/maker.js/test/svg.js

Build 2022 01 26

---

packages/maker.js/src/core/layout.ts

handle layout for only one item

---

packages/maker.js/package-lock.json
packages/maker.js/package.json
packages/maker.js/src/core/model.ts

Fix captions offset
